### ISSUE TITLE
"Nope: Missing catch or finally after try"

### ISSUE THREAD

**Issue by Alujjdnd** [codetheweb/muse#777] opened 2022-08-19 15:43 UTC
**What's happening?**
After setting up the bot on my VPS, both through the Docker and Node method, I get the error "Nope: Missing catch or finally after try" in discord chat when using /play.

**Logs**

No errors show up when running the Docker container or Node script (through both NPM and Yarn). All output are just normal messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/26786974/185655957-cdb783e1-3a05-4bac-9403-d54c9e8d5834.png)

**Additional context**
Worked for a few days, and just started to throw this error today.

**Runtime**
I'm running Muse:
- [x] Directly from the cloned repository
- [x] Inside a Docker container
- [x] Something else (please elaborate)
   - Also using Node directly

**Versions**
- Muse: Latest (v2.1.3)
- Docker (if applicable): 20.10.12, build 20.10.12-0ubuntu4
- OS: Ubuntu 22.04 LTS
- Node.js: 8.11.0
- ffmpeg: 4.4.2-0ubuntu0.22.04.1

**Comment by dwaynehulsman** [comment] 2022-08-19 18:33
Having the same problems

**Comment by nullstalgia** [comment] 2022-08-19 19:21
Same issue. I'm really wondering what's up with these random bugs that occur with no code changes.

**Comment by UAChronos** [comment] 2022-08-19 19:44
Same here

**Comment by Maikel1990** [comment] 2022-08-19 21:49
Issue seems to like related to this https://github.com/fent/node-ytdl-core/issues/1110#issuecomment-1220753734

**Comment by sypion** [comment] 2022-08-19 21:52
Duplicate of [#774](https://github.com/codetheweb/muse/issues/774)

**Comment by codetheweb** [comment] 2022-08-19 23:26
As @sypion said this is a duplicate of #774.

**Closed by codetheweb** 2022-08-19 23:26 UTC
Labels: support
