### ISSUE TITLE
Give access to commands text from docker container

### ISSUE THREAD

**Issue by DarthLeo1000YT** [codetheweb/muse#833] opened 2022-11-23 16:38 UTC
Give access to the commands folder via the docker container to make it possible to edit the text that the bot uses.

Alternatively, add the nano text editor so people can exec into the container and edit it from there.

**Comment by codetheweb** [comment] 2022-11-24 19:47
Duplicate of https://github.com/codetheweb/muse/issues/319.

You can always fork this repo and change the text as well. :)

**Closed by codetheweb** 2022-11-24 19:47 UTC
