### ISSUE TITLE
Configurable voice channel leave behavior

### ISSUE THREAD

**Issue by Xenomer** [codetheweb/muse#513] opened 2022-02-11 15:57 UTC
Currently, the bot automatically leaves the voice channel if either the queue ends or all the participants leave the channel. It would be useful if this behavior was changeable with a config option, either set to a timeout or disable altogether.

I'd like to have the bot as a 24/7 "chime in if you want" kind of music bot and as I host this myself server bandwidth or performance are not an issue.

**Comment by codetheweb** [comment] 2022-02-11 17:10
Duplicate of https://github.com/codetheweb/muse/issues/481.

Happy to accept a PR. 😃

**Closed by codetheweb** 2022-02-11 17:10 UTC
