### ISSUE TITLE
not enough session remaining to spawn 1 shard and some other issues

### ISSUE THREAD

**Issue by mirko8054** [codetheweb/muse#1010] opened 2024-03-30 13:34 UTC
Trying to get Muse to work, quickly installed it last night before getting to sleep, in run it in Docker. Got the bot in my server and upon testing it, some stuff is off. The query assisted search doesnt work, the bot seems to crash after 5 seconds of playing music, the day after (right now) i get this error in the container logs: https://i.imgur.com/p9iMbkW.png 
Any help?

**Comment by codetheweb** [comment] 2024-04-09 03:50
Hmm, could you please post some logs?

**Comment by gknoop** [comment] 2024-05-03 06:52
> Trying to get Muse to work, quickly installed it last night before getting to sleep, in run it in Docker. Got the bot in my server and upon testing it, some stuff is off. The query assisted search doesnt work, the bot seems to crash after 5 seconds of playing music, the day after (right now) i get this error in the container logs: https://i.imgur.com/p9iMbkW.png Any help?

I'm actually having a similar issue right now. it'll handle 2-ish queries for songs from Spotify, then it peaces out. most recently, it went offline with no tangible info about the error. I've tried reinviting the bot to no avail. the only thing that seems to work is restarting it. @codetheweb by any chance, does the bot need any special privileges when you set it up in the Dev portal? I was surprised I didn't see anything in the documentation about enabling any of the Privileged Gateway Intents.

**Comment by gknoop** [comment] 2024-05-04 04:11
> Hmm, could you please post some logs?

As a follow-up to my previous message, here's something more definitive that I just pulled from my logs, following a crash:
```
- Applying database migrations...
✔ Database migrations applied.
- 📡 connecting to Discord...
✔ Ready! Invite the bot with https://discordapp.com/oauth2/authorize?client_id=[...]&scope=bot%20applications.commands&permissions=36700160
DiscordAPIError[50006]: Cannot send an empty message
    at handleErrors (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:152:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SequentialHandler.runRequest (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:399:20)
    at SequentialHandler.queueRequest (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:169:11)
    at REST.request (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/REST.ts:343:20)
    at async VoiceChannel.send (/usr/app/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:162:15)
    at default.onAudioPlayerIdle (/usr/app/src/services/player.ts:585:9) {
  requestBody: {
    files: [],
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: [],
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined
    }
  },
  rawError: { message: 'Cannot send an empty message', code: 50006 },
  code: 50006,
  status: 400,
  method: 'POST',
  url: 'https://discord.com/api/v10/channels/[...]/messages'
}

Node.js v18.7.0
========================================
========================================
================= muse =================
========================================
=========== Made with 🎶 by ============
==== https://github.com/codetheweb =====
========================================
========================================

Running version 2.8.1 built on 4/28/2024 (commit cc1f18bc196fe1b5acb6023dc23ab42f43b41ba7)

🔧 Need help? https://github.com/codetheweb/muse/discussions/new

🐛 Bug? https://github.com/codetheweb/muse/issues/new
✨ New feature? https://github.com/codetheweb/muse/issues/new
☕ Discussion? https://github.com/codetheweb/muse/discussions/new
💰 Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb
```

**Comment by gknoop** [comment] 2024-05-07 21:02
Update: I've confirmed that adjusting the bot's settings for "wait after queue empties" and "leave if no listeners" has no effect. It would appear that it simply leaves when it's been playing for any amount of time and runs out of songs. Further, it would appear this ties back into #1004 so it might be worth merging the two.

**Comment by BarkerB** [comment] 2024-06-13 05:20
> ninja edit: interestingly, it would appear that enabling all of the Privileged Gateway Intents (as I'd done with other music bots) seems to have rectified the issue. will report back if it stops working again.

Just wanted to chime in and say that adding these intents didn't seem to fix the issue for me unfortunately. Still crashes as soon as the queue becomes empty

**Comment by codetheweb** [comment] 2024-07-18 05:04
I can't reproduce this on the latest version (2.9.0) so I'm closing for now. Feel free to re-open if it's still happening.

**Closed by codetheweb** 2024-07-18 05:04 UTC
Labels: support
