### ISSUE TITLE
Enhancement: Localization

### ISSUE THREAD

**Issue by Dan-Mizu** [codetheweb/muse#986] opened 2024-01-05 00:34 UTC
I understand that one of the unique aspects of the Muse bot is that it is mid-western, but it would be a useful feature to move the end-user facing strings to a separate file that could be edited by the deployer or perhaps even a full on localization feature where the community could pitch in to localize the strings to different languages. That might be out of scope, so a simple file with the strings capable of being changed could suffice.

**Comment by codetheweb** [comment] 2024-01-07 23:08
Duplicate of https://github.com/codetheweb/muse/issues/319

**Closed by codetheweb** 2024-01-07 23:08 UTC
Labels: support
