### ISSUE TITLE
Muse does not come up if connected to any servers

### ISSUE THREAD

**Issue by annotated-driftwood** [codetheweb/muse#649] opened 2022-05-13 15:13 UTC
Muse starts just fine and provides a link to attach the bot to a server, but as soon as the bot is added to any server the app crashes attempting to run `esmo "src/scripts/migrate-and-start.ts"` 

[output.txt](https://github.com/codetheweb/muse/files/8688928/output.txt)

**Comment by codetheweb** [comment] 2022-05-14 00:54
Duplicate of https://github.com/codetheweb/muse/issues/637, closed by https://github.com/codetheweb/muse/releases/tag/v2.0.0.

**Closed by codetheweb** 2022-05-14 00:54 UTC
