### ISSUE TITLE
cant play any song

### ISSUE THREAD

**Issue by sishere23** [codetheweb/muse#957] opened 2023-07-29 05:53 UTC
**What's happening?**
Concisely describe what's going wrong.

**Logs**

TypeError: filterWrapper is not iterable
discord-muse-1  |     at Object.exports.parseFilters (/usr/app/node_modules/ytsr/lib/utils.js:23:29)
discord-muse-1  |     at module.exports (/usr/app/node_modules/ytsr/lib/main.js:60:24)
discord-muse-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
discord-muse-1  |     at KeyValueCacheProvider.wrap (/usr/app/src/services/key-value-cache.ts:53:20)
discord-muse-1  |     at run (/usr/app/node_modules/p-queue/dist/null:109:36)
discord-muse-1  | 2023-07-29T05:51:05.885Z muse [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
discord-muse-1  | 2023-07-29T05:51:06.192Z muse [WS => Shard 0] Heartbeat acknowledged, latency of 307ms.
discord-muse-1  | 2023-07-29T05:51:47.136Z muse [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
discord-muse-1  | 2023-07-29T05:51:47.446Z muse [WS => Shard 0] Heartbeat acknowledged, latency of 31->
```

```

**Screenshots**

**Additional context**

**Runtime**
I'm running Muse:
- [yes ] Directly from the cloned repository
- [ yes] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 3.4
- Docker (if applicable):yes
- OS:Ubuntu
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by codetheweb** [comment] 2023-07-30 03:53
Duplicate of https://github.com/codetheweb/muse/issues/948.

**Closed by codetheweb** 2023-07-30 03:53 UTC
Labels: support
