### ISSUE TITLE
Basic feature: internationalization

### ISSUE THREAD

**Issue by matteoturini** [codetheweb/muse#815] opened 2022-10-22 23:21 UTC
Would be nice to be able to translate the bot to other languages

**Comment by matteoturini** [comment] 2022-10-22 23:22
[i18n](https://www.npmjs.com/package/i18n) could be used

**Comment by codetheweb** [comment] 2022-10-22 23:32
Duplicate of https://github.com/codetheweb/muse/issues/319.

**Closed by codetheweb** 2022-10-22 23:32 UTC
