### ISSUE TITLE
Required Permission?

### ISSUE THREAD

**Issue by BennyDaBee** [codetheweb/muse#631] opened 2022-04-24 04:42 UTC
**What's happening?**
When I try to start the bot, it throws out an error and then stops the process. I have given the bot every role I can think of under the sun and it will not start at all. I kicked it, reinvited it with every box ticked and still wont run. 

**Logs**

```
D[50001]: Missing Access
    at C.runRequest (file:///usr/app/node_modules/@discordjs/rest/dist/index.mjs:7:557)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C.queueRequest (file:///usr/app/node_modules/@discordjs/rest/dist/index.mjs:5:3022)
    at async file:///usr/app/src/bot.ts:113:13
    at async Promise.all (index 0)
    at async Client.<anonymous> (file:///usr/app/src/bot.ts:111:9) {
  rawError: { message: 'Missing Access', code: 50001 },
  code: 50001,
  status: 403,
  method: 'put',
  url: 'https://discord.com/api/v9/applications/886949922765668392/guilds/250536489899786240/commands',
  requestBody: {
    files: undefined,
    json: [
      {
        name: 'clear',
        description: 'clears all songs in queue except currently playing song',
        options: [],
        default_permission: undefined
      },
      {
        name: 'config',
        description: 'configure bot settings',
        options: [
          {
            type: 1,
            name: 'set-playlist-limit',
            description: 'set the maximum number of tracks that can be added from a playlist',
            options: [Array]
          },
          {
            type: 1,
            name: 'set-role',
            description: 'set the role that is allowed to use the bot',
            options: [Array]
          },
          {
            type: 1,
            name: 'set-wait-after-queue-empties',
            description: 'set the time to wait before leaving the voice channel when queue empties',
            options: [Array]
          },
          {
            type: 1,
            name: 'set-leave-if-no-listeners',
            description: 'set whether to leave when all other participants leave',
            options: [Array]
          },
          {
            type: 1,
            name: 'get',
            description: 'show all settings',
            options: []
          }
        ],
        default_permission: undefined
      },
      {
        name: 'disconnect',
        description: 'pause and disconnect Muse',
        options: [],
        default_permission: undefined
      },
      {
        name: 'favorites',
        description: 'add a song to your favorites',
        options: [
          {
            type: 1,
            name: 'use',
            description: 'use a favorite',
            options: [Array]
          },
          {
            type: 1,
            name: 'list',
            description: 'list all favorites',
            options: []
          },
          {
            type: 1,
            name: 'create',
            description: 'create a new favorite',
            options: [Array]
          },
          {
            type: 1,
            name: 'remove',
            description: 'remove a favorite',
            options: [Array]
          }
        ],
        default_permission: undefined
      },
      {
        name: 'fseek',
        description: 'seek forward in the current song',
        options: [
          {
            choices: undefined,
            autocomplete: undefined,
            type: 3,
            name: 'time',
            description: 'an interval expression or number of seconds (1m, 30s, 100)',
            required: true
          }
        ],
        default_permission: undefined
      },
      {
        name: 'move',
        description: 'move songs within the queue',
        options: [
          {
            max_value: undefined,
            min_value: undefined,
            choices: undefined,
            autocomplete: undefined,
            type: 4,
            name: 'from',
            description: 'position of the song to move',
            required: true
          },
          {
            max_value: undefined,
            min_value: undefined,
            choices: undefined,
            autocomplete: undefined,
            type: 4,
            name: 'to',
            description: 'position to move the song to',
            required: true
          }
        ],
        default_permission: undefined
      },
      {
        name: 'now-playing',
        description: 'shows the currently played song',
        options: [],
        default_permission: undefined
      },
      {
        name: 'pause',
        description: 'pause the current song',
        options: [],
        default_permission: undefined
      },
      {
        name: 'play',
        description: 'play a song',
        options: [
          {
            choices: undefined,
            autocomplete: true,
            type: 3,
            name: 'query',
            description: 'YouTube URL, Spotify URL, or search query',
            required: true
          },
          {
            name: 'immediate',
            description: 'add track to the front of the queue',
            required: false,
            type: 5
          },
          {
            name: 'shuffle',
            description: "shuffle the input if you're adding multiple tracks",
            required: false,
            type: 5
          },
          {
            name: 'split',
            description: 'if a track has chapters, split it',
            required: false,
            type: 5
          }
        ],
        default_permission: undefined
      },
      {
        name: 'queue',
        description: 'show the current queue',
        options: [
          {
            max_value: undefined,
            min_value: undefined,
            choices: undefined,
            autocomplete: undefined,
            type: 4,
            name: 'page',
            description: 'page of queue to show [default: 1]',
            required: false
          }
        ],
        default_permission: undefined
      },
      {
        name: 'remove',
        description: 'remove songs from the queue',
        options: [
          {
            max_value: undefined,
            min_value: undefined,
            choices: undefined,
            autocomplete: undefined,
            type: 4,
            name: 'position',
            description: 'position of the song to remove [default: 1]',
            required: false
          },
          {
            max_value: undefined,
            min_value: undefined,
            choices: undefined,
            autocomplete: undefined,
            type: 4,
            name: 'range',
            description: 'number of songs to remove [default: 1]',
            required: false
          }
        ],
        default_permission: undefined
      },
      {
        name: 'resume',
        description: 'resume playback',
        options: [],
        default_permission: undefined
      },
      {
        name: 'seek',
        description: 'seek to a position from beginning of song',
        options: [
          {
            choices: undefined,
            autocomplete: undefined,
            type: 3,
            name: 'time',
            description: 'an interval expression or number of seconds (1m, 30s, 100)',
            required: true
          }
        ],
        default_permission: undefined
      },
      {
        name: 'shuffle',
        description: 'shuffle the current queue',
        options: [],
        default_permission: undefined
      },
      {
        name: 'skip',
        description: 'skip the next songs',
        options: [
          {
            max_value: undefined,
            min_value: undefined,
            choices: undefined,
            autocomplete: undefined,
            type: 4,
            name: 'number',
            description: 'number of songs to skip [default: 1]',
            required: false
          }
        ],
        default_permission: undefined
      },
      {
        name: 'next',
        description: 'skip to the next song',
        options: [],
        default_permission: undefined
      },
      {
        name: 'stop',
        description: 'stop playback, disconnect, and clear all songs in the queue',
        options: [],
        default_permission: undefined
      },
      {
        name: 'unskip',
        description: 'go back in the queue by one song',
        options: [],
        default_permission: undefined
      }
    ]
  }
}
file:///usr/app/node_modules/execa/lib/error.js:59
error = new Error(message);
        ^

Error: Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts
    at makeError (file:///usr/app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/app/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///usr/app/src/scripts/run-with-database-url.ts:5:3 {
  shortMessage: 'Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts',
  command: 'esmo src/scripts/migrate-and-start.ts',
  escapedCommand: 'esmo "src/scripts/migrate-and-start.ts"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Screenshots**

**Additional context**

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [x] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 1.9.0
- Docker (if applicable): 20.10.12
- OS: Ubuntu 20.24

**Comment by codetheweb** [comment] 2022-04-24 17:13
Are you using the invite URL generated by Muse?

**Comment by CivDylan** [comment] 2022-05-08 00:39
@codetheweb im using the proper url and still getting the same response

**Comment by codetheweb** [comment] 2022-05-08 20:20
Bot is currently broken; this is a duplicate of https://github.com/codetheweb/muse/issues/637.

**Closed by codetheweb** 2022-05-08 20:20 UTC
Labels: support
